version: '3.8'
services:
  mysql:
    image: mysql:8
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: gclass
    volumes:
      - db_data:/var/lib/mysql
      - ./db/sql:/docker-entrypoint-initdb.d
    ports:
      - '3306:3306'
  backend:
    build: ./backend
    depends_on:
      - mysql
    environment:
      DB_HOST: mysql
      DB_USER: root
      DB_PASS: root
      DB_NAME: gclass
      JWT_SECRET: supersecret
      UPLOAD_DIR: uploads
      PORT: 5000
    ports:
      - '5000:5000'
    volumes:
      - ./backend/uploads:/usr/src/app/uploads
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    depends_on:
      - backend
    ports:
      - '3000:80'
volumes:
  db_data:
